#!/usr/bin/env python3
"""
Generator for the SLEEF-style Payne-Hanek 2/π table used by the SIMD
f64 sin/cos slow path.

This is a port of the algorithm in SLEEF's `src/gencoef/mkrempitab.c`
(by Naoki Shibata, Boost Software License 1.0). The original C
generator is in the SLEEF source tree; this Python reimplementation
uses mpmath (in place of MPFR) and emits hexfloat C literals that
round-trip exactly into our table header.

Algorithm summary
-----------------

For each input exponent ``i`` in [55, 1024), produce 4 doubles
``rpi0, rpi1, rpi2, rpi3`` such that for any double ``a`` with
``ilogb(a) == i``, the sum ``a · (rpi0 + rpi1 + rpi2 + rpi3)``
computed with Double-Double precision gives ``(a / (2π)) mod 1`` to
~106 bits — i.e. the fractional part of ``a / (2π)``. From that the
caller extracts:

    n     = round(alpha · 4)            -> quadrant mod 4
    rho   = alpha · 4 − n               -> in [-0.5, 0.5]
    r     = rho · π/2                   -> reduced argument in [-π/4, π/4]

Each entry's 4 chunks are computed by:

    ex     = max(-52, i − 53)
    target = ((0.5/π) · 2^ex)  mod 1     # frac part of (0.5/π) · 2^ex
    target = target / 2^ex               # back-scale to original mag

For ``i > 700`` the table entries are multiplied by 2^64 (and the
SIMD caller correspondingly scales the input down by 2^-64) to keep
the DD multiplication's hi register from overflowing.

The 4 chunks are successive ``removelsb``-rounded residuals of
``target``: rpi0 = removelsb(float(target)); rpi1 = removelsb(float(
target − rpi0)); etc. ``removelsb`` masks off the lowest mantissa bit
so adjacent chunks remain independent and DD addition stays exact.

The runtime extraction step requires reading bits of the DD result at
positions −1 and −2 (for the quadrant) — these are always within
DD's ~106-bit precision regardless of input magnitude, which is what
makes the table-based approach handle the full f64 range.

Usage
-----

    python3 numpy/_core/src/umath/payne_hanek_table.py > \
        numpy/_core/src/umath/payne_hanek_simd_table.h

Requires `mpmath`. The generated table is ~32 KB (969 entries × 4
doubles × 8 bytes = ~31 KB).
"""
from __future__ import annotations

import struct
import sys

# Where the SLEEF table starts. For ``ilogb(a) < I_MIN`` the input is
# small enough that the regular fast-path Cody-Waite reduction handles
# it correctly — no table lookup needed.
I_MIN = 55
I_MAX = 1024

# Threshold above which we pre-scale the table by 2^64 (and the kernel
# scales the input down by 2^-64) to keep the DD multiplication within
# range.
I_SCALE_THRESHOLD = 700
SCALE_M = -64


def _remove_lsb(d: float) -> float:
    """Clear the lowest mantissa bit. Keeps adjacent chunks independent
    so the DD running sum stays exact when accumulating them."""
    if d == 0.0:
        return d
    bits = struct.unpack("<Q", struct.pack("<d", d))[0]
    bits &= 0xFFFFFFFFFFFFFFFE
    return struct.unpack("<d", struct.pack("<Q", bits))[0]


def _dbl_to_c(x: float) -> str:
    """Emit a double as a C hexfloat literal (round-trips exactly)."""
    if x == 0.0:
        return "0x0p+0"
    return x.hex()


def main() -> int:
    import mpmath
    mpmath.mp.prec = 2048
    rpi = mpmath.mpf(1) / 2 / mpmath.pi  # 0.5/π

    print("/* Auto-generated by numpy/_core/src/umath/payne_hanek_table.py.")
    print(" * Do not edit by hand.  Algorithm port of SLEEF's mkrempitab.c,")
    print(" * Boost Software License 1.0 (c) Naoki Shibata.")
    print(" *")
    print(" * Table format: for each input exponent i in [55, 1024), 4")
    print(" * doubles c0..c3 such that for any double a with ilogb(a) == i,")
    print(" * DD-summing a·c_i gives (a/(2π)) mod 1 to ~106 bits.")
    print(" *")
    print(" * Entries with i > 700 are pre-scaled by 2^64; the SIMD caller")
    print(" * compensates by scaling the input down by 2^-64 (otherwise the")
    print(" * DD multiplication's hi component would overflow).")
    print(" */")
    print("#ifndef _NPY_UMATH_PAYNE_HANEK_SIMD_TABLE_H")
    print("#define _NPY_UMATH_PAYNE_HANEK_SIMD_TABLE_H")
    print()
    print(f"#define NPYV_PH_SIMD_I_MIN              {I_MIN}")
    print(f"#define NPYV_PH_SIMD_I_MAX              {I_MAX}")
    print(f"#define NPYV_PH_SIMD_I_SCALE_THRESHOLD  {I_SCALE_THRESHOLD}")
    print(f"#define NPYV_PH_SIMD_SCALE_M            {SCALE_M}")
    print(f"#define NPYV_PH_SIMD_CHUNKS             4")
    print()
    print("/* table[(i - I_MIN) * 4 + k] is chunk k for input exponent i. */")
    print(f"static const double npyv__ph_simd_table"
          f"[({I_MAX} - {I_MIN}) * 4] = {{")

    for i in range(I_MIN, I_MAX):
        M = SCALE_M if i > I_SCALE_THRESHOLD else 0
        ex = max(-52, i - 53)
        x = mpmath.mpf(2) ** ex
        y = x * rpi
        xrpi = y - mpmath.floor(y)
        xrpi = xrpi / x
        xrpi = xrpi * mpmath.mpf(2) ** (-M)

        chunks = []
        for _ in range(3):
            c = _remove_lsb(float(xrpi))
            chunks.append(c)
            xrpi = xrpi - mpmath.mpf(c)
        chunks.append(float(xrpi))

        line = "    " + ", ".join(_dbl_to_c(c) for c in chunks) + ","
        line += f"  /* i = {i} */"
        print(line)

    print("};")
    print()
    print("#endif /* _NPY_UMATH_PAYNE_HANEK_SIMD_TABLE_H */")
    return 0


if __name__ == "__main__":
    sys.exit(main())
